### ISSUE TITLE
colors not taking effect

### ISSUE THREAD

**Issue by mybigman** [arcticicestudio/nord-xresources#10]
hi there.

I followed your steps however when running htop its still the exact same look as before.

running `xrdb -query` lists the colors, so they are being applied just no change in appearance :/

**Comment by arcticicestudio** [comment]
Hi @mybigman, which terminal do you use? It might be possible that you're using a terminal that doesn't make use of _Xorg_ resources. Most modern terminal come with own themes preferences while only some older terminal like _xterm_ or [_(u)rxvt_][archw] are the ones that take these colors into account.

[archw]: https://wiki.archlinux.org/index.php/Rxvt-unicode

**Comment by mybigman** [comment]
I am using kitty

**Comment by arcticicestudio** [comment]
Looks like _kitty_ also provides themes [through a color table][ref] that allows to define the 16 base colors. There's https://github.com/kovidgoyal/kitty/issues/647 where the _kitty_ maintainer answered that the app doesn't make use of platform specific configurations which includes _xresources_. That sounds logical, otherwise it wouldn't be possible to provide support for different OS without the requirement that each platform must provide some kind of theme API.
Anyway, an official _Nord_ port for _kitty_ has already been requested in https://github.com/arcticicestudio/nord/issues/104 as well as https://github.com/arcticicestudio/nord/issues/113 and both issue authors also proposed a theme. Maybe you can take a look at their themes to use it for yourself until the port project is available 😊

Closing this issue for now since it should be resolved now and it also not related to _xresources_.

[ref]: https://sw.kovidgoyal.net/kitty/conf.html?highlight=theme#the-color-table
