### ISSUE TITLE
Prompt used

### ISSUE THREAD

**Issue by mainrs** [arcticicestudio/nord-xresources#8]
I really like the prompt! Mind posting the `PROMPT`env var or the files used to create it?

**Comment by arcticicestudio** [comment]
Nice to see you like it :smile: 

It is available in my dotfile repository [igloo][] as [prompt][] script and currently designed for Bash version >=4.

![gh-8-prompt-git](https://user-images.githubusercontent.com/7836623/45925430-6553a880-bf15-11e8-8150-b5c668aaae26.png)

It includes full support for the official bundled [git-prompt][] which [must be imported in your `~/.bashrc` or `~/.bash_profile`][git-prompt-import] and will be automatically activated when changing into a git repository, otherwise it'll be hidden and the prompt adapts to a more compact style.

[igloo]: https://github.com/arcticicestudio/igloo
[prompt]: https://github.com/arcticicestudio/igloo/blob/develop/snowblocks/bash/core/prompt
[git-prompt]: https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh
[git-prompt-import]: https://github.com/arcticicestudio/igloo/blob/ac9f7bf7a3e931ff4825757a428e9c00fbb45543/snowblocks/bash/bootstrap#L129-L133
